#! /usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

if [[ -f graphx.zip ]]; then
  rm graphx.zip
fi

zip -r graphx src test haxelib.json build.hxml hmm.json LICENSE README.md

haxelib submit graphx.zip
